#define COMPONENT main
#include "script_mod.hpp"

// #define DEBUG_MODE_FULL
// #define DISABLE_COMPILE_CACHE
// #define CBA_DEBUG_SYNCHRONOUS
// #define ENABLE_PERFORMANCE_COUNTERS

#ifdef DEBUG_ENABLED_IMPROVED_ACE_ARSENAL_CATEGORY
    #define DEBUG_MODE_FULL
#endif

#ifdef DEBUG_SETTINGS_IMPROVED_ACE_ARSENAL_CATEGORY
    #define DEBUG_SETTINGS DEBUG_SETTINGS_IMPROVED_ACE_ARSENAL_CATEGORY
#endif

#include "script_macros.hpp"
