name = "Improved-ACE-Arsenal-Category"
prefix = "improved_ace_arsenal_category"
mainprefix = "x"

[properties]
author = "johnb43"
url = "https://github.com/johnb432"

[files]
include = [
    "CHANGELOG.md",
    "meta.cpp",
    "mod.cpp",
    "LICENSE",
    "README.md"
]
